In [1]:
import altair as alt
import gcsfs
import pandas as pd


GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/ntd_explore/"

alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [2]:
GCS = "gs://calitp-analytics-data/data-analyses/ntd/"
orig_df = pd.read_parquet(
    f"{GCS}raw_transit_performance_metrics_data.parquet",
    filesystem = gcsfs.GCSFileSystem()
)
orig_df.dtypes

agency_name           object
agency_status         object
city                  object
mode                  object
service               object
ntd_id                object
reporter_type         object
reporting_module      object
state                 object
primary_uza_name      object
year                  object
upt                    int64
vrh                    int64
vrm                    int64
opexp_total            int64
RTPA                  object
_merge              category
dtype: object

In [3]:
orig_df.head(2)

,agency_name,agency_status,city,mode,service,ntd_id,reporter_type,reporting_module,state,primary_uza_name,year,upt,vrh,vrm,opexp_total,RTPA,_merge
0,City of Porterville (COLT) - Transit Department,Active,Porterville,Demand Response,Purchased Transportation,90198,Building Reporter,Urban,CA,"Porterville, CA",2019,13112,2997,43696,572799,Tulare County Association of Governments,both
1,City of Porterville (COLT) - Transit Department,Active,Porterville,Demand Response,Purchased Transportation,90198,Building Reporter,Urban,CA,"Porterville, CA",2020,11523,3669,48138,686165,Tulare County Association of Governments,both

# what columns are needed
* RTPA - shows `rtpa_name`, not `rtpa_name_split`
* just read in the subset of columns needed, these metrics are precalculated

In [4]:
crosswalk = pd.read_parquet(
    f"{GCS_FILE_PATH}crosswalk2.parquet", 
    filesystem=gcsfs.GCSFileSystem(),
    columns = ["ntd_id_2022", "rtpa_name"]
).rename(columns = {"ntd_id_2022": "ntd_id"})

df = pd.read_parquet(
    f"{GCS_FILE_PATH}annual.parquet",
    # should only certain columns be read in? now this table is much larger
    filesystem=gcsfs.GCSFileSystem(),
    columns = [
        "source_agency", "agency_status", "source_city", 
        "mode", "type_of_service", "ntd_id", 
        "reporter_type", "reporting_module", "source_state", "primary_uza_name",
        "year", "unlinked_passenger_trips", "vehicle_revenue_hours", "vehicle_revenue_miles",
        "operating_expenses_total",
    ]
).merge(
    crosswalk,
    on = "ntd_id",
    how = "left"
)

# mode should be mode_full_name
# service refers to type_of_service_full name 
df.dtypes

source_agency               object
agency_status               object
source_city                 object
mode                        object
type_of_service             object
ntd_id                      object
reporter_type               object
reporting_module            object
source_state                object
primary_uza_name            object
year                         Int64
unlinked_passenger_trips     Int64
vehicle_revenue_hours        Int64
vehicle_revenue_miles        Int64
operating_expenses_total     Int64
rtpa_name                   object
dtype: object

In [5]:
df2 = df[df.year <= 2023].reset_index(drop=True)

In [6]:
orig_df.shape, df2.shape

((2091, 17), (2676, 16))

In [7]:
# there are some additional ones in the dbt model
m1 = pd.merge(
    orig_df[["ntd_id"]].drop_duplicates(),
    df2[["ntd_id"]].drop_duplicates(),
    on = ["ntd_id", ],
    how = "outer",
    indicator=True
)
    
m1._merge.value_counts()

_merge
both          168
right_only     15
left_only       0
Name: count, dtype: int64

In [8]:
m1[m1._merge == "right_only"]

    ntd_id      _merge
0    30109  right_only
1    30131  right_only
99   90235  right_only
101  90238  right_only
106  90249  right_only
164  90313  right_only
165  90314  right_only
170  91092  right_only
171  99256  right_only
172  99262  right_only
173  99292  right_only
174  99316  right_only
175  99358  right_only
176  99364  right_only
182  99452  right_only

These still get aggregated by agency/mode/tos.

In [9]:
import B3_ntd_utils as ntd_utils

val_cols = [
    "opex_per_vrh",
    "opex_per_vrm",
    "upt_per_vrh",
    "upt_per_vrm",
    "opex_per_upt",
]

label_dict ={
    'unlinked_passenger_trips':"Unlinked Passenger Trips",
    'vehicle_revenue_miles':"Vehicle Revenue Miles",
    'vehicle_revenue_hours':"Vehicle Revenue Hours",
    'operating_expenses_total':"Operating Expense Total",
    'opex_per_vrh':"Operating Expense per Vehicle Revenue Hours",
    'opex_per_vrm':"Operating Expense per Vehicle Revenue Miles",
    'opex_per_upt':"Operating Expense per Unlinked Passenger Trips",
    'upt_per_vrh':"Unlinked Passenger Trips per Vehicle Revenue Hours",
    'upt_per_vrm':"Unlinked Passenger Trips per Vehicle Revenue Miles",
}

def make_long(df: pd.DataFrame, group_cols: list, value_cols: list):
    """
    melts dataframes to get all the metrics into a single column for better charting
    do the labeling here too
    this function can sit in notebook
    """
    df_long = df[group_cols + value_cols].melt(
        id_vars=group_cols,
        value_vars=value_cols,
    )

    df_long = df_long.assign(
        label = df_long.variable.map(label_dict)
    )

    return df_long

by_agency = ntd_utils.calculate_efficiency_metrics_by_group(
    df2, ["ntd_id", "source_agency", "rtpa_name", "year"]
).pipe(
    make_long, 
    ["ntd_id", "source_agency", "rtpa_name", "year"], 
    val_cols
)
# agency_name...is this renamed from source_agency?

In [10]:
by_mode = ntd_utils.calculate_efficiency_metrics_by_group(
    df2, ["mode", "rtpa_name", "year"]
).pipe(
    make_long, 
    ["mode", "rtpa_name", "year"], 
    val_cols
)

by_mode

,mode,rtpa_name,year,variable,value,label
0,CB,El Dorado County Transportation Commission,2018,opex_per_vrh,196.13,Operating Expense per Vehicle Revenue Hours
1,CB,El Dorado County Transportation Commission,2019,opex_per_vrh,193.45,Operating Expense per Vehicle Revenue Hours
2,CB,El Dorado County Transportation Commission,2020,opex_per_vrh,188.83,Operating Expense per Vehicle Revenue Hours
3,CB,El Dorado County Transportation Commission,2021,opex_per_vrh,241.0,Operating Expense per Vehicle Revenue Hours
4,CB,El Dorado County Transportation Commission,2022,opex_per_vrh,221.87,Operating Expense per Vehicle Revenue Hours
...,...,...,...,...,...,...
2905,YR,San Diego Association of Governments,2019,opex_per_upt,8.94,Operating Expense per Unlinked Passenger Trips
2906,YR,San Diego Association of Governments,2020,opex_per_upt,11.37,Operating Expense per Unlinked Passenger Trips
2907,YR,San Diego Association of Governments,2021,opex_per_upt,18.29,Operating Expense per Unlinked Passenger Trips
2908,YR,San Diego Association of Governments,2022,opex_per_upt,21.62,Operating Expense per Unlinked Passenger Trips
2909,YR,San Diego Association of Governments,2023,opex_per_upt,17.74,Operating Expense per Unlinked Passenger Trips

In [11]:
by_tos = ntd_utils.calculate_efficiency_metrics_by_group(
    df2, ["type_of_service", "rtpa_name", "year"]
).pipe(
    make_long, 
    ["type_of_service", "rtpa_name", "year"], 
    val_cols
)

by_tos

,type_of_service,rtpa_name,year,variable,value,label
0,DO,Del Norte Local Transportation Commission,2018,opex_per_vrh,56.63,Operating Expense per Vehicle Revenue Hours
1,DO,Del Norte Local Transportation Commission,2019,opex_per_vrh,99.19,Operating Expense per Vehicle Revenue Hours
2,DO,Del Norte Local Transportation Commission,2020,opex_per_vrh,168.52,Operating Expense per Vehicle Revenue Hours
3,DO,Del Norte Local Transportation Commission,2021,opex_per_vrh,512.08,Operating Expense per Vehicle Revenue Hours
4,DO,Del Norte Local Transportation Commission,2022,opex_per_vrh,447.41,Operating Expense per Vehicle Revenue Hours
...,...,...,...,...,...,...
1645,TX,Transportation Agency for Monterey County,2019,opex_per_upt,NaN,Operating Expense per Unlinked Passenger Trips
1646,TX,Transportation Agency for Monterey County,2020,opex_per_upt,NaN,Operating Expense per Unlinked Passenger Trips
1647,TX,Transportation Agency for Monterey County,2021,opex_per_upt,NaN,Operating Expense per Unlinked Passenger Trips
1648,TX,Transportation Agency for Monterey County,2022,opex_per_upt,NaN,Operating Expense per Unlinked Passenger Trips
1649,TX,Transportation Agency for Monterey County,2023,opex_per_upt,37.13,Operating Expense per Unlinked Passenger Trips

## Chart Ideas

* existing charts put cost-efficiency, service-effectiveness metrics in separate headings, and under those headings, there are by agency, by mode, by TOS
* re-organize this to put cost-efficiency, service-effectiveness metrics side-by-side for agency, then side-by-side for mode, side-by-side for TOS?

In [34]:
test_tos= by_tos[by_tos.rtpa_name.str.contains("Del Norte")]#.variable.value_counts()

test_tos2 = test_tos.sort_values(["rtpa_name", "type_of_service", "variable", "year"]).groupby(
    ["rtpa_name", "type_of_service", "variable"]
).agg({
    "value": lambda x: list(x)
}).reset_index()

In [23]:
from great_tables import GT
import gt_extras as gte
import polars as pl

In [38]:
test_tos3 = pl.from_pandas(test_tos2)
(GT(test_tos3, rowname_col="variable")
    .fmt_nanoplot(columns="value")
)

GT(_tbl_data=shape: (5, 4)
┌─────────────────────────────────┬─────────────────┬──────────────┬─────────────────────────┐
│ rtpa_name                       ┆ type_of_service ┆ variable     ┆ value                   │
│ ---                             ┆ ---             ┆ ---          ┆ ---                     │
│ str                             ┆ str             ┆ str          ┆ list[f64]               │
╞═════════════════════════════════╪═════════════════╪══════════════╪═════════════════════════╡
│ Del Norte Local Transportation… ┆ DO              ┆ opex_per_upt ┆ [17.79, 22.17, … 18.04] │
│ Del Norte Local Transportation… ┆ DO              ┆ opex_per_vrh ┆ [56.63, 99.19, … 138.6] │
│ Del Norte Local Transportation… ┆ DO              ┆ opex_per_vrm ┆ [4.17, 6.3, … 10.56]    │
│ Del Norte Local Transportation… ┆ DO              ┆ upt_per_vrh  ┆ [3.18, 4.47, … 7.68]    │
│ Del Norte Local Transportation… ┆ DO              ┆ upt_per_vrm  ┆ [0.23, 0.28, … 0.59]    │
└─────────────────────────────────┴─────────────────┴──────────────┴─────────────────────────┘, _body=<great_tables._gt_data.Body object at 0x7a113c35d250>, _boxhead=Boxhead([ColInfo(var='rtpa_name', type=<ColInfoTypeEnum.default: 1>, column_label='rtpa_name', column_align='left', column_width=None), ColInfo(var='type_of_service', type=<ColInfoTypeEnum.default: 1>, column_label='type_of_service', column_align='left', column_width=None), ColInfo(var='variable', type=<ColInfoTypeEnum.stub: 2>, column_label='variable', column_align='left', column_width=None), ColInfo(var='value', type=<ColInfoTypeEnum.default: 1>, column_label='value', column_align='center', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x7a113c35ac50>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x7a113c35ab50>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x7a113c336850>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x7a113c3229d0>, _formats=[<great_tables._gt_data.FormatInfo object at 0x7a113c323150>], _substitutions=[], _col_merge=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)